---
apiVersion: v1
data:
  values: |
    aws: {}
    bastion: {}
    clusterName: mywcl
    controlPlane:
      replicas: 3
    machinePools:
    - instanceType: m5.xlarge
      maxSize: 10
      minSize: 3
      name: machine-pool0
      rootVolumeSizeGB: 300
    network:
      availabilityZoneUsageLimit: 3
    organization: carillan
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: mywcl
  name: mywcl-userconfig
  namespace: org-carillan
