---
apiVersion: v1
data:
  values: |
    clusterName: mywcl
    organization: carillan
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    giantswarm.io/cluster: mywcl
  name: mywcl-default-apps-userconfig
  namespace: org-carillan
