apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
  - files:
    - values=cluster_config.yaml
    name: ${cluster_name}-0.21.0-config
    namespace: org-${organization}
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
patchesStrategicMerge:
  - version_patch_config.yaml
resources:
  - ../template