apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  giantswarm.io/managed-by: flux
kind: Kustomization
configMapGenerator:
  - files:
    - values=wc_config.yaml
    name: ${cluster_name}-wc-config
    namespace: org-${organization}
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
  - patch_config.yaml
resources:
  - ../../../../../../../../bases/clusters/capa/template/
