apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  giantswarm.io/managed-by: flux
kind: Kustomization
configMapGenerator:
  - files:
    - values=wc_config.yaml
    name: ${cluster_name}-wc-config
    namespace: org-${organization}
generatorOptions:
  disableNameSuffixHash: true
patches:
  - patch: |
      - op: add
        path: /spec/extraConfigs/-
        value:
          name: ${cluster_name}-wc-config
          namespace: org-${organization}
          priority: 111
          
    target:
      group: application.giantswarm.io
      kind: App
      name: \${cluster_name}
      namespace: org-\${organization}
resources:
  - ../../../../../../../../bases/clusters/capa/v0.21.0/
