apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grizzly-clusters-example
  namespace: default
spec:
  interval: 1m
  path: ./management-clusters/grizzly/organizations/carillan/workload-clusters/example/mapi
  postBuild:
    substitute:
      cluster_name: example
      cluster_release: 0.21.0
      default_apps_release: 0.15.0
      organization: carillan
  prune: false
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: carillan-gitops-tuto
  timeout: 2m
